from pydantic import BaseModel, Field


class SampleData(BaseModel):
    """Representing a single data point from the manufacturing sensor stream."""

    features: dict[str, float] = Field(
        ..., description="Key-value pairs of the 170 sensor readings."
    )
    label: int | None = Field(
        None,
        description="Binary classification target: 0 (non-failure) or 1 (failure).",
    )
    index: int = Field(..., description="Sequential position index in the data stream.")
    is_drifted: bool = Field(
        False,
        description="Flag indicating if concept drift was injected at this sample.",
    )


class PredictionResult(BaseModel):
    """Output generated by the prediction service."""

    prediction: int = Field(..., description="Class predicted by the model: 0 or 1.")
    probability: float = Field(..., description="Model confidence score P(failure).")
    residual: float = Field(
        ...,
        description="Prediction residual score, e.g., |probability - label|.",
    )
    cost: float = Field(
        ..., description="Asymmetric misclassification cost accrued by this prediction."
    )


class DriftSignal(BaseModel):
    """Output generated by the drift detection ensemble service."""

    is_drift: bool = Field(
        ..., description="Consensus indicator specifying if concept drift is triggered."
    )
    detector_votes: dict[str, bool] = Field(
        ..., description="Boolean votes from all individual statistical detectors."
    )
    consensus_ratio: float = Field(
        ..., description="The ratio of detectors voting for drift (k/n)."
    )
    sample_index: int = Field(
        ..., description="The index in the stream where the consensus was calculated."
    )


class ExplanationResult(BaseModel):
    """Output generated by the explainability service (SHAP & DiCE)."""

    shap_values: dict[str, float] | None = Field(
        None, description="Per-feature TreeSHAP attribution values."
    )
    counterfactuals: list[dict[str, float]] | None = Field(
        None, description="List of generated counterfactual feature edits."
    )
    cfe_validity: float | None = Field(
        None,
        description="Ratio of CFEs that successfully flipped the prediction.",
    )
    cfe_proximity: float | None = Field(
        None, description="Average L1 proximity distance to the original sample."
    )
    cfe_sparsity: int | None = Field(
        None, description="Average number of features changed in counterfactuals."
    )


class ExperimentMetrics(BaseModel):
    """Aggregated evaluation metrics for a full experimental run."""

    total_cost: float = Field(
        ..., description="Sum of misclassification costs over the stream."
    )
    recall: float = Field(
        ..., description="Model failure detection rate (critical for PdM)."
    )
    precision: float = Field(..., description="Model predictive precision.")
    f1_score: float = Field(..., description="Harmonic mean of precision and recall.")
    roc_auc: float = Field(..., description="Area under the ROC curve.")
    drift_fpr: float = Field(
        ..., description="False positive rate of drift detection during stable phases."
    )
    drift_latency: int | None = Field(
        None, description="Number of samples between drift onset and detection."
    )
    cfe_validity_rate: float = Field(
        ..., description="Overall validity rate of generated counterfactuals."
    )
    cfe_avg_proximity: float = Field(
        ..., description="Average L1 proximity of generated counterfactuals."
    )
    cfe_avg_sparsity: float = Field(
        ..., description="Average sparsity of generated counterfactuals."
    )
    cfe_feature_overlap: float | None = Field(
        None, description="Pre/Post-drift counterfactual feature alignment/stability."
    )
